apiVersion: v1
kind: Namespace
metadata:
  name: tienda
  labels:
    app.kubernetes.io/name: tienda
    app.kubernetes.io/part-of: tienda-perritos
    app.kubernetes.io/managed-by: kubectl
    environment: production