apiVersion: v1
kind: ConfigMap
metadata:
  name: tienda-config
  namespace: tienda
  labels:
    app.kubernetes.io/name: tienda
    app.kubernetes.io/part-of: tienda-perritos

data:
  NODE_ENV: "production"

  APP_PORT: "3001"

  DB_HOST: "mysql-service"

  DB_PORT: "3306"

  DB_NAME: "tienda_perritos"