apiVersion: v1
kind: Secret
metadata:
  name: tienda-secret
  namespace: tienda
  labels:
    app.kubernetes.io/name: tienda
    app.kubernetes.io/part-of: tienda-perritos

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: "CAMBIAR_ROOT_PASSWORD"
  MYSQL_USER: "CAMBIAR_USUARIO"
  MYSQL_PASSWORD: "CAMBIAR_PASSWORD"