apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tienda
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: tienda-perritos

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: tienda-perritos

    spec:
      containers:
        - name: mysql

          image: mysql:8.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: tienda-config
                  key: DB_NAME

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tienda-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: tienda-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tienda-secret
                  key: MYSQL_PASSWORD

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: mysql-storage
          emptyDir: {}