apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tienda
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: tienda-perritos

spec:
  type: ClusterIP

  selector:
    app: mysql

  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306